export const ServiceUrl = "http://localhost:3000/api" 
export const verificationLink = "http://localhost:3000/Setpassword"
export const DomainUrl = "http://localhost:3000/Dashboard"  
export const user = "bcsm-f20-141@superior.edu.pk" 
export const pass = "student123*" 